### ISSUE TITLE
无数据

### ISSUE THREAD

**Issue by returnight** [Aufree/PHPHub-iOS#10]
直接运行代码 无数据。

**Comment by Aufree** [comment]
API 的问题，已修复。

**Comment by returnight** [comment]
试过了，还是没有数据

**Comment by returnight** [comment]
测试key的问题？

**Comment by returnight** [comment]
#define Client_id       @"kHOugsx4dmcXwvVbmLkd"
#define Client_secret   @"PuuFCrF94MloSbSkxpwS"
