### ISSUE TITLE
测试过了，还是无数据

### ISSUE THREAD

**Issue by returnight** [Aufree/PHPHub-iOS#11]
# define Client_id       @"kHOugsx4dmcXwvVbmLkd"
# define Client_secret   @"PuuFCrF94MloSbSkxpwS"

是测试key的问题 ？

**Comment by Aufree** [comment]
测试接口的问题，过段时间再开放测试 API 接口。

**Comment by returnight** [comment]
OK，你的中文文档去申请开发key的连接不对

**Comment by sanyueyuxincao** [comment]
测试环境，扫码登录，提示登录失败，请重试

**Comment by Aufree** [comment]
@returnight @sanyueyuxincao 看下这里：https://laravel-china.org/topics/3097
