### ISSUE TITLE
 which  username and password for 'https://github.com' when i run pod install

### ISSUE THREAD

**Issue by chenjiongzhou** [Aufree/PHPHub-iOS#12]
<img width="527" alt="611bb3ae-3fbf-43fd-9abd-3e45b3763163" src="https://cloud.githubusercontent.com/assets/7410783/21651792/fb5771e6-d2e4-11e6-9fc3-7cad981a775a.png">

**Comment by wwwang89** [comment]
me too。。pod file太老了，这个文件也找不到了

**Comment by Yaojia809** [comment]
It should be your own Github account's username and password
