### ISSUE TITLE
pop 'MTLFMDBAdapter' 404

### ISSUE THREAD

**Issue by coldmn3** [Aufree/PHPHub-iOS#13]
https://github.com/summerblue/MTLFMDBAdapter
请修复下。

**Comment by wwwang89** [comment]
暂时用这个吧，https://github.com/tanis2000/MTLFMDBAdapter.git

**Comment by wwwang89** [comment]
楼主，跟新一下项目工程代码吧，，好多偏僻的pods没法用了，，有些版本低了，都废弃了。。

**Comment by callmewenxi** [comment]
同样的错误,怎么处理?

**Comment by kalsolio** [comment]
➜  PHPHub-iOS git:(master) ✗ pod install
Analyzing dependencies
Pre-downloading: `MTLFMDBAdapter` from `https://github.com/tanis2000/MTLFMDBAdapter`
Pre-downloading: `QRCodeReaderViewController` from `https://github.com/zhengjinghua/MQRCodeReaderViewController.git`, commit `0b6af2738ea2cc393060704554b9ac2ec7f0bd53`
[!] Unable to satisfy the following requirements:

- `Mantle (= 1.5.5)` required by `Podfile`
- `Mantle (~> 2.0)` required by `MTLFMDBAdapter (0.3.2)`

**Comment by wujunze** [comment]
我也遇到了这个问题
![image](https://user-images.githubusercontent.com/12997869/31370604-b56b338c-ad51-11e7-99dc-4e595ffc6303.png)
