### ISSUE TITLE
Crash after launched at "NSBundle *imageBundle = [NSBundle bundleWithURL:url];' -- SVProgressHUD.m -- line 335

### ISSUE THREAD

**Issue by PhoenixCheung** [Aufree/phphub-ios#3]
Crash after launched at "NSBundle *imageBundle = [NSBundle bundleWithURL:url];' -- SVProgressHUD.m -- line 335

**Comment by Aufree** [comment]
Did you run this project in simulator?

**Comment by Fisher-Fang** [comment]
我也是差不多的原因崩了，不支持模拟器么？

**Comment by Aufree** [comment]
@Fisher-Fang 因为从 Xcode 7 开始就支持免证书真机调试, 并且应用需要扫码进行登录, 所以此问题一直没去管它.

**Comment by Fisher-Fang** [comment]
@Aufree 真机提示因为Jpush的APP_KEY为空，然后配置错误，还是崩溃

**Comment by Fisher-Fang** [comment]
![qq20151202-0 2x](https://cloud.githubusercontent.com/assets/12724076/11528004/146ef97a-991f-11e5-9148-27ce4a56917f.png)

**Comment by Fisher-Fang** [comment]
![Uploading QQ20151202-0@2x.png…]()

**Comment by Fisher-Fang** [comment]
@Aufree 折腾了40分钟才跑起来，似乎需要把Pod工程下的DateTools.bundle和SVProgressHUD.bundle复制到主工程下才行，否则你那个获取Bundle路径的方法报异常，然后就崩溃了。

**Comment by Panway** [comment]
我直接这样改的
```
        UIImage* infoImage = [UIImage imageNamed:@"SVProgressHUD.bundle/info.png"];
        UIImage* successImage = [UIImage imageNamed:@"SVProgressHUD.bundle/success.png"];
        UIImage* errorImage = [UIImage imageNamed:@"SVProgressHUD.bundle/error.png"];
```

**Comment by X-my** [comment]
Manually adding the bundle file works for me.

**Comment by Aufree** [comment]
是的, 添加缺失的 bundle 是最直接的修复方式
