### ISSUE TITLE
pod install DSL Error

### ISSUE THREAD

**Issue by arkilis** [Aufree/PHPHub-iOS#6]
Pod::DSLError
![image](https://cloud.githubusercontent.com/assets/1528028/11917786/1e97a482-a762-11e5-883c-bf6a1c896f5a.png)

Any clue on this? Thx

**Comment by crazytom26** [comment]
下载下来后secretConstant.h文件缺失

**Comment by Aufree** [comment]
Remove your Podfile.lock file, and try again.

**Comment by Aufree** [comment]
@crazytom26 you should run this command to create a SecretConstant.h file. 

```shell
cp PHPHub/Constants/SecretConstant.example.h PHPHub/Constants/SecretConstant.h
```

**Comment by wwwang89** [comment]
我的个去，，作者搞那么多Third lib有 的好偏，，，更新了几个小时都没下来，，，😢
