### ISSUE TITLE
缺少SecretConstant.h文件

### ISSUE THREAD

**Issue by IsLandSea** [Aufree/phphub-ios#7]
执行完命令打开后，缺少SecretConstant.h文件

**Comment by angrilove** [comment]
见 http://aufree.github.io/PHPHub-iOS/

> 配置项目
> 
> 项目的一些较为隐秘的信息都放在了 SecretConstant.h 中, 因此你需要先创建自己的 SecretConstant.h 文件, 运行以下命令进行创建.
> 
> $ cp PHPHub/Constants/SecretConstant.example.h PHPHub/Constants/SecretConstant.h
